import { createElement } from 'lwc';
import Lwc_2312_eg2_input2cal from 'c/lwc_2312_eg2_input2cal';

describe('c-lwc-2312-eg2-input2-cal', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-2312-eg2-input2-cal', {
            is: Lwc_2312_eg2_input2cal
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});