import { createElement } from 'lwc';
import Lwc_1701_Eg1_CSSEg from 'c/lwc_1701_Eg1_CSSEg';

describe('c-lwc-1701-eg1-css-eg', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-1701-eg1-css-eg', {
            is: Lwc_1701_Eg1_CSSEg
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});